### ISSUE TITLE
Keypad disappears.

### ISSUE THREAD

**Issue by Thoky81** [mattsaxon/HASS-Jablotron80#19] opened 2020-08-30 19:37 UTC
Hi @mattsaxon,

can you please update the docs with how to install it in HACS?
I am getting some errors: Repostitory structure for V1.0 is not compliant

Thanks

**Comment by mattsaxon** [comment] 2020-08-30 20:33
Sorry, I’m struggling with the same issue. I’ve never got it to install via HACS.

**Comment by Thoky81** [comment] 2020-08-30 20:53
OK no problem.I have updated manually, but I am now missing the keypad in lovelace.. I have just the buttons. Any idea?

**Comment by mattsaxon** [comment] 2020-08-31 10:52
I've reverted the changes I just merged as it seems I didn't look hard enough and some additional changes have snuck into the verison I tested. @FraBoCH can you take a look at why this is occurring as I've had just taken the latest version and I have the same issue as Thoky81

**Comment by FraBoCH** [comment] 2020-08-31 11:38
OK I'll check.
If I'm not mistaking, it depends on the configuration parameters. The keypad only appears if you chose to enter the code every time you arm or disarm your alarm.
31 août 2020 12:52:30 mattsaxon <notifications@github.com>:

**Comment by Thoky81** [comment] 2020-08-31 15:12
@FraBoCH Hi, yes I can confirm that if I chose to require the code to arm/disarm the keypad is there. Thanks

**Comment by FraBoCH** [comment] 2020-08-31 17:55
Thanks for the confirmation @Thoky81! So it's not a but @mattsaxon, it's a feature ;-) 
I think you can safely restore my PR, unless you prefer to test it & fine tune it further. I'm open to suggestion.

**Comment by mattsaxon** [comment] 2020-08-31 18:21
I’ll check behaviour,  but my config was no code to lock, but required a code to unlock.

**Comment by FraBoCH** [comment] 2020-08-31 18:29
Ok. I'll check also on my side. The change I made on that matter was in commit dc2f3af2b3265ea985d5ad1cfe19f022bb7f656a 
Basically, it only returns "None" (which makes the HA UI remove the keypad) if and only if both code_arm_required and code_disarm_required are set to false.

**Comment by FraBoCH** [comment] 2020-08-31 19:01
I can confirm setting code_disarm_required to True shows the keypad, if you have a "code" configured. If you don't configure any code however, the keypad is not shown. 
This is due to the following code in code_format method present in your initial commit: 
        if code is None:
            return None

If we should support a setup without any code, we can simply change this return and check if other places of the code should be adapted too. 

BTW when entering the wrong code in the keypad, there is no feedback to the user which is not ideal.

**Comment by mattsaxon** [comment] 2020-09-06 14:46
@FraBoCH actually, you are correct whilst the behaviour has changed, it is in fact correct... at least for me. However I can't accept the latest commits because when setting, the status does not show as arming. It still shows as unarmed whilst it is setting

**Comment by FraBoCH** [comment] 2020-09-06 18:24
@mattsaxon you're totally right about the arming state ! There is a very small bug at line 279 (should be self._state and not state). I've fixed it already on my fork (see commit https://github.com/FraBoCH/HASS-Jablotron80/commit/fc42f4a725c59f2652b32edcb80cb3c733238e4f), but don't really know what's the best way to share it with you now that the PR is merged and you reverted the commits afterwards. Let me know what's the best way to contribute !

**Comment by mattsaxon** [comment] 2020-09-12 13:23
@FraBoCH, I've removed my reversion, so you should be able to submit a standard PR now with that bug fix.

Thanks.

**Comment by FraBoCH** [comment] 2020-09-12 18:33
@mattsaxon OK perfect. I've just submitted the PR to fix that. Happy to contribute to your project !

**Comment by FraBoCH** [comment] 2020-10-03 18:29
@mattsaxon I think this issue should be closed.

**Comment by mattsaxon** [comment] 2022-01-30 11:42
Please move to https://github.com/tahvane1/jablotron80 as this integration is no longer maintained. That repo is more functional and fixes this issue

**Closed as completed by mattsaxon** 2022-01-30 11:42 UTC
