### ISSUE TITLE
Integration 'Jablotron80' not found

### ISSUE THREAD

**Issue by booroondook-eng** [mattsaxon/HASS-Jablotron80#32] opened 2021-06-18 14:13 UTC
My configuration:
```
Version | core-2021.6.5
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.9
Operating System Family | Linux
Operating System Version | 4.19.0-16-amd64
CPU Architecture | x86_64
GitHub API | ok
Installed Version | 1.12.4
Stage | running
```
configuration.yaml (fragment):
```
alarm_control_panel:
  - platform: Jablotron80
    serial_port: /dev/serial/by-id/usb-Silicon_Labs_JABLOTRON_serial_interface_0001-if00-port0
```
Folder 
`custom_components/Jablotron80`
with files:
```
__init__.py
alarm_control_panel.py
manifest.json
```
Problem: Check configuration reports:
**_Configuration invalid_**
and
**_Platform error alarm_control_panel.Jablotron80 - Integration 'Jablotron80' not found._**
I tried to rename "Jablotron80" to "jablotron" and "Jablotron" (including the folder name), but result always is the same.

**Comment by FraBoCH** [comment] 2021-06-21 20:55
I can confirm the "platform" attribute must match the folder name you put in folder `custom_components`.
As you are running HA 2021.06.*, please make sure you have a version number in the manifest. I've already added that in my PR #24 but it is not merged yet.
If you didn't do that already, try restarting HA before adding the configuration section in configuration.yaml and the restart once again.
Then, please check the HA logs to see if any error appears.

**Comment by ghost** [comment] 2021-06-22 08:27
> I can confirm the "platform" attribute must match the folder name you put in folder `custom_components`.

Yes. My folder is:
`.../custom_components/jablotron`
and it contains these files:
```
__init__.py
alarm_control_panel.py
manifest.json
```
HA's configuration.yaml contains these strings:
```
alarm_control_panel:
  - platform: jablotron
    serial_port: /dev/ttyUSB0
```
> As you are running HA 2021.06.*, please make sure you have a version number in the manifest. I've already added that in my PR #24 but it is not merged yet.

Yes. My manifest.json:
```
{
        "domain": "Jablotron80",
        "name": "Jablotron 80 Component",
        "version": "0.0.1.0",
        "documentation": "https://github.com/mattsaxon/hass-jablotron80",
        "issue_tracker": "https://github.com/mattsaxon/hass-jablotron80/issues",
        "codeowners": ["@mattsaxon"],
        "version": "1.0.0"
        "codeowners": ["@mattsaxon"]
}
```
> If you didn't do that already, try restarting HA before adding the configuration section in configuration.yaml and the restart once again.

I did HA restarting **before** confguration changes. But I cannot restart HA **after** changes because HA tells about invalid configuration and cannot be restarted (see attached screenshots, please).
![2021-06-22 11_20_58-Window](https://user-images.githubusercontent.com/71794974/122890055-046a9080-d34c-11eb-9b43-6b3c882b13da.png)
![Безымянный](https://user-images.githubusercontent.com/71794974/122890832-b73aee80-d34c-11eb-8138-8fb2faea623e.png)

> Then, please check the HA logs to see if any error appears.

 Therere are no any logs becase HA restart is impossible with configuration shown above.
P.S. HA is 2021.6.6 version

**Comment by FraBoCH** [comment] 2021-06-22 18:56
Hi @booroondookZ I suggest you change to the following setup which works for me in HA 2021.6.6: 
1. Rename the folder in custom_components to "Jablotron80"
2. In configuration.yaml use: `platform: Jablotron80`
3. Use this as your manifest.json content: https://github.com/FraBoCH/HASS-Jablotron80/blob/master/custom_components/Jablotron80/manifest.json

If it still fails, restart without any entry in the configuration.yaml before adding it.
I hope it will work.

**Comment by ghost** [comment] 2021-06-23 08:51
> Hi @booroondookZ I suggest you change to the following setup which works for me in HA 2021.6.6:
> 
Thank you very much! Your method is working to me. But there are some nuances.
After I made changes to the files and then clicked the "Check configuration" button, I again got the same errors that I wrote about earlier. The only difference was that in these errors "Jablotron80" was shown, instead of "jablotron". 
And then I made the following steps:
1. I have commented out the corresponding lines in configuration.yaml file.
2. I clicked on the "Check configuration" button and made sure there were no errors.
3. I clicked on the "Restart Home Assistant" button, and then (I have access to the server via Samba) reopened "configuration.yaml" file and removed the comments (at this time the server had not finished its restart yet).
4. After restarting and getting the server up and running, I made sure that everything works. And what's more: pressing the "Check configuration" button again does not give an error.

**Comment by FraBoCH** [comment] 2021-06-23 13:13
OK great! 

23 juin 2021 10:51:13 booroondookZU ***@***.***>:

>> Hi @booroondookZ[https://github.com/booroondookZ] I suggest you change to the following setup which works for me in HA 2021.6.6:
>> 
> Thank you very much! Your method is working to me. But there are some nuances.
> After I made changes to the files and then clicked the "Check configuration" button, I again got the same errors that I wrote about earlier. The only difference was that in these errors "Jablotron80" was shown, instead of "jablotron".
> And then I made the following steps:
> 
1. > I have commented out the corresponding lines in configuration.yaml file.
2. > I clicked on the "Check configuration" button and made sure there were no errors.
3. > I clicked on the "Restart Home Assistant" button, and then (I have access to the server via Samba) reopened "configuration.yaml" file and removed the comments (at this time the server had not finished its restart yet).
4. > After restarting and getting the server up and running, I made sure that everything works. And what's more: pressing the "Check configuration" button again does not give an error.

**Comment by mattsaxon** [comment] 2021-09-01 17:13
@FraBoCH thanks for fixing this and putting in the PR. I have now merged.

**Closed as completed by mattsaxon** 2021-09-01 17:13 UTC
